# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 16:38
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20171010_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('start', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
        ),
    ]
