# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_analysiscategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysiscategory',
            name='analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='backend.Analysis'),
        ),
    ]
