# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-11 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_analysistimeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysistimeseries',
            name='scanlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.ScanList'),
        ),
    ]
